//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityPincode
    {
        public int CityPincodeId { get; set; }
        public Nullable<int> CDCityId { get; set; }
        public int Cityid { get; set; }
        public string Pincode { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    
        public virtual CashDeliveryCity CashDeliveryCity { get; set; }
        public virtual city city { get; set; }
    }
}
