//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class featureproduct
    {
        public int lfeatureproductid { get; set; }
        public Nullable<int> lproductid { get; set; }
        public Nullable<int> ladminid { get; set; }
        public Nullable<System.DateTime> dentrydatetime { get; set; }
        public Nullable<System.DateTime> dlasteditdate { get; set; }
        public Nullable<int> llasteditadminid { get; set; }
        public string clastipaddress { get; set; }
        public Nullable<byte> bdeleteflag { get; set; }
    }
}
