//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class giftdetail
    {
        public int lgiftdetailid { get; set; }
        public Nullable<System.DateTime> dddate { get; set; }
        public Nullable<int> loccassionid { get; set; }
        public string cmessage { get; set; }
        public Nullable<System.DateTime> dentrydatetime { get; set; }
        public string clastipaddress { get; set; }
        public Nullable<int> lorderid { get; set; }
    }
}
