//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentdetail
    {
        public int lpaymentid { get; set; }
        public Nullable<int> lorderid { get; set; }
        public Nullable<int> lresponsecode { get; set; }
        public string cpgtransactionid { get; set; }
        public string cmerchanttransactionid { get; set; }
        public Nullable<byte> bpaymentstatus { get; set; }
        public Nullable<System.DateTime> dentrydatetime { get; set; }
    }
}
