//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pbkup
    {
        public int lproductid { get; set; }
        public Nullable<int> lcategoryid { get; set; }
        public string cproductname { get; set; }
        public Nullable<int> lauthorid { get; set; }
        public Nullable<int> lpublisherid { get; set; }
        public string cisbn { get; set; }
        public Nullable<int> lpages { get; set; }
        public string cmetatitle { get; set; }
        public string cmetadescription { get; set; }
        public Nullable<int> ltaxclassid { get; set; }
        public Nullable<double> lweight { get; set; }
        public Nullable<double> lprice { get; set; }
        public string cdescription { get; set; }
        public string cimage { get; set; }
        public string cbinding { get; set; }
        public Nullable<int> ladminid { get; set; }
        public Nullable<System.DateTime> dentrydatetime { get; set; }
        public string clastipaddress { get; set; }
        public Nullable<int> llasteditadminid { get; set; }
        public Nullable<System.DateTime> dlasteditdate { get; set; }
        public Nullable<byte> bdeleteflag { get; set; }
        public string StockStatus { get; set; }
        public string Ext { get; set; }
        public Nullable<int> ProductDiscount { get; set; }
        public Nullable<int> lManufacturerid { get; set; }
        public string DeliveryStatus { get; set; }
    }
}
