//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificationHead
    {
        public int specifactionid { get; set; }
        public Nullable<int> lproductid { get; set; }
        public string Specificationhead1 { get; set; }
        public Nullable<int> lcategoryid { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
    }
}
