//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class traderorderdescription
    {
        public int lorderdescriptionid { get; set; }
        public string cbillingfirstname { get; set; }
        public string cbillinglastname { get; set; }
        public string cbillingaddress1 { get; set; }
        public string cbillingaddress2 { get; set; }
        public string cbillingcityname { get; set; }
        public string cbillingcontactno { get; set; }
        public string cshippingfirstname { get; set; }
        public string cshippinglastname { get; set; }
        public string cshippingaddress1 { get; set; }
        public string cshippingaddress2 { get; set; }
        public string cshippingcityname { get; set; }
        public string cshippingcontactno { get; set; }
        public string cbillingzipcodeno { get; set; }
        public string cshippingzipcodeno { get; set; }
        public Nullable<int> lbillingstateid { get; set; }
        public Nullable<int> lshippingstateid { get; set; }
        public string cshipmentby { get; set; }
        public string cshipmentdetails { get; set; }
    }
}
