//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userlogin
    {
        public int luserid { get; set; }
        public string ccontactaddress { get; set; }
        public string cloginname { get; set; }
        public string cpassword { get; set; }
        public string cdisplayname { get; set; }
        public string ccontactno { get; set; }
        public string cemailaddress { get; set; }
        public Nullable<byte> badd { get; set; }
        public Nullable<byte> bedit { get; set; }
        public Nullable<byte> bdelete { get; set; }
        public Nullable<byte> lusertype { get; set; }
        public Nullable<int> lcityid { get; set; }
        public Nullable<int> ladminid { get; set; }
        public Nullable<System.DateTime> dentrydatetime { get; set; }
        public string clastipaddress { get; set; }
        public Nullable<int> llasteditadminid { get; set; }
        public Nullable<System.DateTime> dlasteditdate { get; set; }
        public Nullable<byte> bstatus { get; set; }
        public Nullable<byte> bdeleteflag { get; set; }
        public string usertype { get; set; }
    }
}
