//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.Product_Image = new HashSet<Product_Image>();
        }
    
        public int VendorId { get; set; }
        public string VendorCode { get; set; }
        public string VendorName { get; set; }
        public string CompanyName { get; set; }
        public string TinNo { get; set; }
        public string VatNo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public int CityId { get; set; }
        public int StateId { get; set; }
        public int CountryId { get; set; }
        public Nullable<decimal> PinCode { get; set; }
        public string EmailId { get; set; }
        public Nullable<decimal> ContactNo { get; set; }
        public string PaymentMethods { get; set; }
        public string DiscountType { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public string DiscountAvailable { get; set; }
        public Nullable<bool> Bdeleteflag { get; set; }
        public Nullable<int> RankingId { get; set; }
        public Nullable<bool> Active { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> Updateddate { get; set; }
        public string cpassword { get; set; }
    
        public virtual city city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Image> Product_Image { get; set; }
    }
}
