//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DataLayer.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestSellerProduct
    {
        public int lBestSellerID { get; set; }
        public Nullable<int> lproductid { get; set; }
        public Nullable<double> ldiscount { get; set; }
        public Nullable<byte> bstatus { get; set; }
        public Nullable<System.DateTime> dentrydatetime { get; set; }
        public string clastipaddress { get; set; }
    }
}
