//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DataLayer.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public category()
        {
            this.specificationdetails = new HashSet<specificationdetail>();
        }
    
        public int lcategoryid { get; set; }
        public string ccategoryname { get; set; }
        public Nullable<int> lundercategoryid { get; set; }
        public string calias { get; set; }
        public Nullable<int> lsupercategoryid { get; set; }
        public Nullable<int> ladminid { get; set; }
        public Nullable<System.DateTime> dentrydatetime { get; set; }
        public Nullable<byte> bdeleteflag { get; set; }
        public string clastipaddress { get; set; }
        public Nullable<int> llasteditadminid { get; set; }
        public Nullable<System.DateTime> dlasteditdate { get; set; }
        public Nullable<int> categoryparent { get; set; }
        public Nullable<byte> lorder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<specificationdetail> specificationdetails { get; set; }
    }
}
