//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DataLayer.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ledger
    {
        public int ledgerId { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string ledgername { get; set; }
        public Nullable<int> accountID { get; set; }
        public Nullable<int> groupID { get; set; }
        public string refrencename { get; set; }
        public Nullable<int> referenceID { get; set; }
        public Nullable<double> openingbalance { get; set; }
        public Nullable<double> dr { get; set; }
        public Nullable<double> cr { get; set; }
        public Nullable<byte> costledgerflag { get; set; }
        public Nullable<int> branchID { get; set; }
        public string ledgercode { get; set; }
        public Nullable<byte> viewflag { get; set; }
        public Nullable<double> drlimit { get; set; }
        public Nullable<byte> dlcheck { get; set; }
    }
}
