//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DataLayer.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class newaddedcity
    {
        public int lAddedCity { get; set; }
        public string caddcityname { get; set; }
        public Nullable<int> laddcountryid { get; set; }
        public Nullable<int> laddstateid { get; set; }
        public string cbillcityname { get; set; }
        public Nullable<int> lbillcountryid { get; set; }
        public Nullable<int> lbillstateid { get; set; }
        public Nullable<int> luserid { get; set; }
        public Nullable<System.DateTime> dentrydatetime { get; set; }
        public string clastipaddress { get; set; }
        public Nullable<byte> bnewstatus { get; set; }
    }
}
