//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DataLayer.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderhistory
    {
        public int lorderhistoryid { get; set; }
        public Nullable<int> luserid { get; set; }
        public Nullable<int> lorderid { get; set; }
        public Nullable<byte> lorderstatusid { get; set; }
        public Nullable<int> lquantity { get; set; }
        public Nullable<System.DateTime> dentrydatetime { get; set; }
        public Nullable<int> lproductid { get; set; }
        public string cremarks { get; set; }
        public Nullable<byte> bdeleteflag { get; set; }
    }
}
