//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DataLayer.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.ProductPrices = new HashSet<ProductPrice>();
            this.specificationdetails = new HashSet<specificationdetail>();
        }
    
        public int lproductid { get; set; }
        public Nullable<int> lcategoryid { get; set; }
        public string cproductname { get; set; }
        public Nullable<int> ltaxclassid { get; set; }
        public string cdescription { get; set; }
        public string cimage { get; set; }
        public Nullable<int> ladminid { get; set; }
        public Nullable<System.DateTime> dentrydatetime { get; set; }
        public string clastipaddress { get; set; }
        public Nullable<int> llasteditadminid { get; set; }
        public Nullable<System.DateTime> dlasteditdate { get; set; }
        public Nullable<byte> bdeleteflag { get; set; }
        public string Ext { get; set; }
        public string DeliveryStatus { get; set; }
        public string ProductAvailable { get; set; }
        public Nullable<bool> VerifiedFlag { get; set; }
        public Nullable<bool> Display { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPrice> ProductPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<specificationdetail> specificationdetails { get; set; }
    }
}
