//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DataLayer.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSize
    {
        public int SizeId { get; set; }
        public string SizeCode { get; set; }
        public string SizeName { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<int> SupID { get; set; }
    }
}
