//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DataLayer.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductColor
    {
        public int colorid { get; set; }
        public string colorcode { get; set; }
        public string colorname { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string colorhexcode { get; set; }
    }
}
