//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DataLayer.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        public int PriceId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public Nullable<decimal> Price1_Discount { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public Nullable<decimal> Price2_Discount { get; set; }
        public Nullable<decimal> Price3 { get; set; }
        public Nullable<decimal> Price3_Discount { get; set; }
    
        public virtual product product { get; set; }
    }
}
