//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DataLayer.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Image
    {
        public int ImageId { get; set; }
        public string OrginalImage { get; set; }
        public string ImageName { get; set; }
        public string Extentsion { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string vendorproductcode { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
