//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DataLayer.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class specificationdetail
    {
        public int Detailid { get; set; }
        public Nullable<int> specifactionid { get; set; }
        public string subtitleName { get; set; }
        public string sDescription { get; set; }
        public Nullable<int> lproductid { get; set; }
        public int lcategoryid { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
    
        public virtual category category { get; set; }
        public virtual product product { get; set; }
    }
}
