//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DataLayer.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class supercategory
    {
        public int lsupercategoryid { get; set; }
        public string csupercategoryname { get; set; }
        public Nullable<System.DateTime> dcreationdate { get; set; }
        public Nullable<int> parentsc { get; set; }
    }
}
