//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DataLayer.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class temptablenew
    {
        public int ltemptableid { get; set; }
        public Nullable<int> lproductid { get; set; }
        public string cproductname { get; set; }
        public string cisbn { get; set; }
        public Nullable<int> lauthorid { get; set; }
        public Nullable<int> lcategoryid { get; set; }
        public Nullable<double> lprice { get; set; }
        public string cguid { get; set; }
        public Nullable<System.DateTime> ddatetime { get; set; }
        public string cimage { get; set; }
        public Nullable<System.DateTime> dentrydatetime { get; set; }
        public Nullable<byte> criteria { get; set; }
    }
}
