//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DataLayer.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class temptabletraderproductid
    {
        public int ltemptableproductid { get; set; }
        public string image { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> taxclassid { get; set; }
        public Nullable<int> currencyid { get; set; }
        public Nullable<int> productid { get; set; }
        public string isbn { get; set; }
        public Nullable<int> authorid { get; set; }
        public Nullable<int> categoryid { get; set; }
        public Nullable<int> publisherid { get; set; }
        public string productname { get; set; }
        public Nullable<System.DateTime> ddatetime { get; set; }
        public string cguid { get; set; }
    }
}
