//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DataLayer.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class traderorderlist
    {
        public int lproductlistid { get; set; }
        public Nullable<int> lproductid { get; set; }
        public Nullable<int> ltraderorderid { get; set; }
        public Nullable<int> lquantity { get; set; }
        public Nullable<double> lprice { get; set; }
        public Nullable<double> ldiscountcouponprice { get; set; }
        public Nullable<int> lcartid { get; set; }
    }
}
