//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DataLayer.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class traderorder
    {
        public int lorderid { get; set; }
        public Nullable<int> ltraderid { get; set; }
        public Nullable<System.DateTime> dentrydatetime { get; set; }
        public Nullable<byte> bdeleteflag { get; set; }
        public Nullable<byte> lorderstatusid { get; set; }
        public Nullable<int> lquantity { get; set; }
        public Nullable<int> lorderdescriptionid { get; set; }
        public Nullable<int> lpaymentmodeid { get; set; }
        public Nullable<int> lpaymenttypeid { get; set; }
        public string cremarks { get; set; }
        public Nullable<byte> bstatusreach { get; set; }
        public Nullable<int> lshippingcharges { get; set; }
        public Nullable<double> lordercharges { get; set; }
        public Nullable<byte> lgiftwrap { get; set; }
        public Nullable<int> ldiscountcouponid { get; set; }
        public Nullable<byte> bnewstatus { get; set; }
        public Nullable<double> ldiscount { get; set; }
        public Nullable<byte> bacceptorder { get; set; }
        public string cpono { get; set; }
    }
}
