//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DataLayer.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public byte LogID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> LogOutDate { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
